services:
  - type: web
    name: amazon-affiliate-bot
    env: docker
    repo: https://github.com/lamenDino/amazon-affiliate-bot
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8192598584:AAHuV4Gv1X9KY0V5RHOYKyxykw4TJuko1Wo
      - key: YOURLS_URL
        sync: false
      - key: YOURLS_SIGNATURE
        sync: false
      - key: AFFILIATE_TAG
        value: ruciferia-21

  - type: web
    name: amazon-affiliate-yourls
    env: docker
    dockerImage: yourls:latest
    envVars:
      - key: YOURLS_DB_HOST
        sync: false
      - key: YOURLS_DB_USER
        value: yourls_user
      - key: YOURLS_DB_PASS
        sync: false
      - key: YOURLS_DB_NAME
        value: yourls
      - key: YOURLS_SITE
        value: https://amazon-affiliate-yourls.onrender.com
      - key: YOURLS_USER
        value: admin
      - key: YOURLS_PASS
        sync: false

databases:
  - name: yourls-database
    databaseName: yourls
    user: yourls_user
